### PR TITLE
Adding PD Support

### PR DESCRIPTION
**Pull request by jbaldo**

### CODE REVIEW

**Comment by basti2342** [comment]
Hey,

what's up with this pull request? Don't you want it to get merged anymore?

Basti

**Comment by jbaldo** [comment]
Hey, I meant to open it against my forked repo's master but accidentally opened against yours. If you're interested, I can reopen but I might be significantly diverging so not sure if it makes sense. For example, I'm using a python scheduler library instead of cron. Also added a docker container for fun.

**Comment by basti2342** [comment]
Oh okay, I will add a link to the README referencing your fork.

**Comment by basti2342** [comment]
Do you have a link for me?

**Comment by jbaldo** [comment]
Here's a diff if you want to take a look:
https://github.com/basti2342/retweet-bot/compare/master...OAKEDU:master

**Pull request closed without merging**
